version: '3.0'

services:
  archsite:
    container_name: archsite
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: bash -c "npm run build && npm run start"
    restart: always
    networks:
      - rabbitmq_go_net
  web:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=83.136.233.209
     - NGINX_PORT=80
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge